language: android
jdk: openjdk8

android:
  components:
    - tools
  licenses:
    - android-sdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_4b990bd60633_key -iv $encrypted_4b990bd60633_iv -in archive.tar.gz.enc -out archive.tar.gz -d
  - tar -xzvf archive.tar.gz
  - chmod +x gradlew

before_script:
  # Suppress output to keep log under Travis limit
  - echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager "tools" > /dev/null
  - echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platform-tools" > /dev/null

script: ./gradlew build

before_cache:
  - rm -f  ${HOME}/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ${HOME}/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - ${HOME}/.gradle/caches/
    - ${HOME}/.gradle/wrapper/
    - ${HOME}/.android/build-cache/

before_deploy: cp app/build/outputs/apk/release/app-release.apk LockWidget.apk

deploy:
  provider: releases
  api_key:
    secure: fnuHnwOgV2JX3Ecu6nEX9duShkVkdpXhJt6XOp9QbKtaSul77TvZe3/O9o/wqN+/00RYaWsBpPp20VX3KbFyAgX5qaKltDYckY+yvrclYlhGXUBFrxJxxN6TLlhL9IPrZPYb08sQaVZwWYPQ1NqFGSZVM3lRD+PyJVful5d525pVtpBAzmi6OGDcLK/FHyx3M4c4IYdn8QKpfTHqsUZ6PoGfiSveMZ4k+DleFME24TQYspc139lL/56aBdSwdoZH+ooKFuZBQ+HBUv4/xbQey/LVrIR//8IjHfoTniMnyFsWG39mxXKVCuVqdIng7UMcx5i1QnHzS0y/F/27aBYUQ+UtmoPgPfuy+k1KgXKEgZQ6ilLP99y8zFT6Q2y+gLgMEdvVs2HhnSl4hNMiQS2ZD4e0XUmpRQS5BA3ZOTLrhubAdrmr0Ihs5gMV+2wIbJvR5UXL8ZTOiXJLfM5gbOvS+EFGf8s9K9nRIpqCWxJqLCyA00jFi7MA/yBk8oHWGTjaJXCdy/pEo4dS/qsa67n7nHIg5C5xwAxGUqYy6niFPLN/yYW2FewqWT0E6r0EC/5A/eVZRQ7IgaCfRi/yZv0cGSGwo2MmEV/qVd1Fdgs0Frf3q8MscbP1T8w/bICiJ97rqq6RBxckbqLsI8yGq24xNdPVUNlkHItOg1FXUo/ehPw=
  file: LockWidget.apk
  on:
    repo: Shingyx/LockWidget
    tags: true

notifications:
  email: false
